export type SkillsType = {title:string,id:number}[];

export const skills:SkillsType = [
    { title: 'JavaScript', id: 1 },
    { title: 'HTML', id: 2 },
    { title: 'CSS', id: 3 },
    { title: 'React.js', id: 4 },
    { title: 'Node.js', id: 5 },
    { title: 'TypeScript', id: 6 },
    { title: 'Git', id: 7 },
    { title: 'REST APIs', id: 8 },
    { title: 'GraphQL', id: 9 },
    { title: 'SQL', id: 10 },
    { title: 'NoSQL', id: 11 },
    { title: 'Docker', id: 12 },
    { title: 'Kubernetes', id: 13 },
    { title: 'AWS', id: 14 },
    { title: 'Azure', id: 15 },
    { title: 'GCP (Google Cloud Platform)', id: 16 },
    { title: 'Python', id: 17 },
    { title: 'Java', id: 18 },
    { title: 'C#', id: 19 },
    { title: 'Ruby on Rails', id: 20 },
    { title: 'PHP', id: 21 },
    { title: 'Agile Methodologies', id: 22 },
    { title: 'CI/CD Pipelines', id: 23 },
    { title: 'Microservices Architecture', id: 24 },
    { title: 'Jenkins', id: 25 },
    { title: 'Terraform', id: 26 },
    { title: 'Ansible', id: 27 },
    { title: 'Webpack', id: 28 },
    { title: 'Parcel', id: 29 },
    { title: 'MongoDB', id: 30 },
    { title: 'PostgreSQL', id: 31 },
    { title: 'MySQL', id: 32 },
    { title: 'Figma', id: 33 },
    { title: 'Adobe XD', id: 34 },
    { title: 'UX/UI Design', id: 35 },
    { title: 'Testing (Jest / Mocha / Cypress)', id: 36 },
    { title: 'Linux', id: 37 },
    { title: 'Bash/Shell Scripting', id: 38 },
    { title: 'Performance Optimization', id: 39 },
    { title: 'Debugging', id: 40 },
    { title: 'Critical Thinking', id: 41 },
    { title: 'Soft Skills', id: 42 },
    { title: 'Collaboration Tools (Slack / Teams)', id: 43 },
    { title: 'Redux', id: 44 },
    { title: 'Next.js', id: 45 },
    { title: 'Angular', id: 46 },
    { title: 'Vue.js', id: 47 },
    { title: 'Tailwind CSS', id: 48 },
    { title: 'Bootstrap', id: 49 },
    { title: 'SASS/SCSS', id: 50 },
    { title: 'Progressive Web Apps (PWAs)', id: 51 },
    { title: 'Mobile Development (React Native / Flutter)', id: 52 },
    { title: 'Web Security Basics', id: 53 },
    { title: 'OAuth', id: 54 },
    { title: 'SSL/TLS', id: 55 },
    { title: 'Version Control (GitHub/GitLab)', id: 56 },
    { title: 'SEO Basics', id: 57 },
    { title: 'Webpack Module Federation', id: 58 },
]  